Extract prefix to static variable in notifications.
EternalCodeTeam/EternalEconomy pull request #50
Opened 2024-10-22 21:13 UTC by VerniQ

2024-10-22 21:33 UTC, Rollczi requested changes

2024-10-22 21:33 UTC, Rollczi commented on eternaleconomy-core/src/main/java/com/eternalcode/economy/config/implementation/messages/MessageConfig.java
> +        "<b><gradient:#00FFA2:#34AE00>ECONOMY</gradient></b> <dark_gray>➤</dark_gray> ";
Remove static

2024-10-22 22:00 UTC, CitralFlo requested changes

2024-10-22 22:00 UTC, CitralFlo commented on eternaleconomy-core/src/main/java/com/eternalcode/economy/command/cooldown/CommandCooldownConfig.java
> +import static com.eternalcode.economy.config.implementation.messages.MessageConfig.*;
We usually don't use `*` in imports. Try to apply MessageConfig via constructor in main class

2024-10-22 22:00 UTC, CitralFlo commented on eternaleconomy-core/src/main/java/com/eternalcode/economy/command/cooldown/CommandCooldownConfig.java
> +        .chat(messagesPrefix + "<white>You must wait <gradient:#00FFA2:#34AE00>{TIME}</gradient> before using /pay again.")
if this import is needed only for this, maybe try package private and access the variable directly or via method. @Rollczi please think if there is a better way to do it

2024-10-22 22:07 UTC, vLuckyyy requested changes
It should be done on the principle of internal placeholder, for example `{PREFIX}` can be used anywhere in the messages, this will allow a little more flexibility, currently you add everywhere, what if someone will have one message set to actionbar and the other to normal chat? I want to have a prefix in the chat and not in the actionbar, then he won't have a choice because you will add a prefix permanently.

2024-10-22 22:08 UTC, Rollczi requested changes
the solution used is based on incorrect assumptions. You can't expect that the prefix will magically be appended to the configuration, to understand this see what the generated config looks like and what happens if you change the prefix in file and reload it

2025-06-27 23:25 UTC, CitralFlo requested changes
@Rollczi @vLuckyyy can it be extracted to notice creation so we do not have to setup {PREFIX} in every message?? Make it available by default for all messages?

2026-04-19 19:12 UTC, closed without merging